### ISSUE TITLE
How can we extract code coverage information of a wasm binary?

### ISSUE THREAD

**Issue by tareq97** [satabin/swam#68]

**Comment by satabin** [comment]
Hi @tareq97,

I am not sure how this is related to swam in particular? Are you asking how to instrument a wasm program to get coverage? Or do you have an instrumented program already and you want to execute it with swam and get coverage out of it? In this case, it depends on how your instrumentation works.

**Comment by tareq97** [comment]
Hi @satabin
Yes, I want to know how to instrument a wasm file to get coverage information using swam?
I am trying to work on a fuzzer for wasm runtime execution. The fuzzer is guided by code coverage so for that code coverage information is needed.

**Comment by satabin** [comment]
Well, there is no way of doing coverage out of the box, you will need to do it yourself.

You can use the [`Transformer`](https://swam.gnieh.org/api/swam/traversal/Transformer.html) to instrument blocks, conditions, and loops, I guess. Or write your own tree traversal if it doesn't fit your purpose. I just thought about a more generic traversal framework that may be easier to use  in some cases, but it's not there yet and I have t think it through. How do you expect your coverage report to look like?

**Comment by tareq97** [comment]
Hi @satabin,

Thanks for the information on Transformer API. Also would like to know more about generic traversal framework.
Below is a list of information that might be considered to be added in the report both at low and high level.

Low-level information such as:
1. List of total instructions in the wasm module. 
2. List of total instruction covered.
3. List of total instructions which are not covered. 
4. List of instructions in a covered in a particular line.
5. List of instructions uncovered in a particular line.

and High-level information such as:
1. Each method in the wasm module and percentage of coverage.

**Comment by satabin** [comment]
Currently the `Transformer` is a one-to-one transformation operation, meaning that one instruction can only be transformed into exactly one instruction. However, in code coverage you don't need to know every instruction but basic block, as in a [CFG](https://swam.gnieh.org/examples/cfg/) since every basic block is atomic if you don't trap anywhere. There is no drop-in solution to do what you want to do that I am aware of, you'll have to come up with your solution. I can only encourage you to check how coverage instrumentation can be done, and then if you have concrete questions on how to do it with Swam (I think the only swam specific part of it, is how to transform instructions), I'd be happy to help you with this. But currently it sounds like you still need to come up with the way you want to instrument your code to get these data.

**Comment by tareq97** [comment]
Just wanted to let the team know about my work progress on the coverage tool,

Still working on understanding the swam code, to look for the right place where to put the code of making a copy of basic blocks information from the CFG and also to record which block is executed and increase the counter on the respective basic blocks index in a hashmap.

**Comment by satabin** [comment]
@tareq97 If you need additions to Swam to cover you need, let me know, I will see how I can add it.

**Comment by tareq97** [comment]
@satabin sure I will let you know. thanks

**Comment by satabin** [comment]
@tareq97 hey, did you sole your problem here? Can I close the ticket?

**Comment by tareq97** [comment]
Sorry for the late reply, I guess this issue can be closed, Also I guess I closed the Issue#69. Hope that it, not an issue.
