### ISSUE TITLE
/dev/random hanging issue

### ISSUE THREAD

**Issue by orestisfl** [satabin/swam#84]
We discussed this in gitter, I can add more details if needed.

I was having issues running swam on my server but not on my laptop. For example using [box.zip](https://github.com/satabin/swam/files/4901667/box.zip) (from #80) and execution stopped abruptly at some point, with cpu utilization diving to 0%.

After all, I traced (also see backtrace: https://pastebin.com/raw/neBzKWav) the issue to this line:
https://github.com/satabin/swam/blob/8f796a2cd169a1d10cb0313370b2c1635b5123b9/wasi/src/swam/runtime/wasi/internal/MiscOps.scala#L45
Which seems to read from `/dev/random`. Running `sudo rm -f /dev/random && sudo ln -sf /dev/urandom /dev/random` (don't do this at home) resolves my issue.

**Comment by satabin** [comment]
Random generator in Swam, indeed uses blocking random generation, as per WASI documentation. I will add an option to make it non-blocking, but default will be blocking as long as the WASI documentation explicitly mentions it. This might then change if they change that in the WASI documentation.

My proposal is to add a `--wasi:non-blocking-rng` option  or similar in the CLI (and its counterpart in the library), so that it becomes non-blocking.

**Comment by monperrus** [comment]
yes, `/dev/urandom` is the way to go.

AFAIU, Swam is not meant to be cryptographically secure, so what having `--wasi:non-blocking-rng` the default behavior to avoid this hard-to-debug behavior in the future?

**Comment by satabin** [comment]
@monperrus Swam intends to follow the spec and documentation. As long as documentation explicitly mentions the random is blocking, then it will stay the default behavior for me in Swam.

**Comment by monperrus** [comment]
ack
